endlessm/hack-sound-server

com.endlessm.HackSoundServer.json.in, com.endlessm.HackSoundServer.service, hack-sound-server, meson.build, meson_options.txt
This is working, but I am creating this pull request to get feedback.
To try this you need to create a file.
$HOME/.var/app/com.endlessm.HackSoundServer/data/hack-sound-server/metadata.json
```
{
"water": {
"sound-file": "water.wav"
}
}
```
and add a sound file (for this example water.wav) in `$HOME/.var/app/com.endlessm.HackSoundServer/data/hack-sound-server/sounds` 
And you can call it by doing
```
gdbus call --session --dest com.endlessm.HackSoundServer --object-path /com/endlessm/HackSoundServer --method com.endlessm.HackSoundServer.PlaySound water
```
=> hack-sound-server: Initial version

README.md, build-flatpak.sh
=> Tools: add build script to create and install the flatpak

src/server.py, src/utils/metadata.py
https://phabricator.endlessm.com/T24260
=> Various follow-up changes

src/utils/misc.py
https://phabricator.endlessm.com/T24205#642379
=> T24205 fixes

src/server.py
https://phabricator.endlessm.com/T24386
=> server: Support volume

data/metadata.json
https://phabricator.endlessm.com/T24523
=> Make gnome-shell hover sounds loop

src/server.py
https://phabricator.endlessm.com/T24426
=> server: Add PlayFull method to override options

src/server.py
It can occur that the StopSound event arrives when the pipeline
is still in NULL or READY. We query the duration of the pipeline
to handle the fade-out effect. However, querying the pipeline
only works during PAUSED or PLAYING. The approach here is to send
an EOS event if the fade-out effect failed but we wait until the
pipeline gets to the PAUSED state.
https://phabricator.endlessm.com/T24523
=> server: Stop loop when StopSound called from during NULL or READY

src/server.py
https://phabricator.endlessm.com/T24610
=> server: Support updating properties on the fly among loops

src/server.py
https://phabricator.endlessm.com/T24669
=> T24669 (only fade on loops)

src/server.py
https://phabricator.endlessm.com/T24811
=> server: Release HackSoundPlayer explicitly

data/metadata.json
The current quests reference sounds that are not in the metadata.
https://phabricator.endlessm.com/T24805
=> data: Add more placeholders for quests

src/server.py
https://phabricator.endlessm.com/T24848
=> server: Change the behavior of PlaySound

data/metadata.json
https://phabricator.endlessm.com/T24930
=> sounds: codeview/ambient/hacking: Fix music path typo

src/server.py
https://phabricator.endlessm.com/T24499
=> server: Stop sound when the caller app dies/closes

data/metadata.json
https://phabricator.endlessm.com/T24884
=> sounds: fizzics: Rename collision sounds to death sounds

data/metadata.json
https://phabricator.endlessm.com/T25052
=> sounds: Add OperatingSystemApp background sound

src/server.py
https://phabricator.endlessm.com/T25111
=> server: Stop sound by event id

src/server.py
https://phabricator.endlessm.com/T25153
=> server: Calculate fade out as a property

src/server.py
When stopping looping sounds with fade_out=0, sometimes the EOS
message was not posted inmediately to the bus. So, instead of
sentind an EOS event, just free the pipeline.
https://phabricator.endlessm.com/T25226
=> server: Free pipeline instead of sending EOS event

data/metadata.json
https://phabricator.endlessm.com/T25151
=> sounds: Tag quests sounds and interferring sounds as "bg"

data/metadata.json
https://phabricator.endlessm.com/T25151
=> Tag a few more sounds as background

src/server.py
Sounds tagged in the metadata with "type": "bg" will have the
following behavior: whenever a sound with this tag is set to play,
the last sound with the "bg" tag will be set to PAUSED; and when
this sound stops, the most recent sound will be resumed (or set
to play).
https://phabricator.endlessm.com/T25151
=> server: Add bg and sfx sounds rule

README.md, bin/hack-sound-server.in, src/server.py, src/utils/loggable.py, src/utils/metadata.py
https://phabricator.endlessm.com/T24927
=> server: Add method to list playing sounds by event id

src/server.py
It avoids causing bottlenecks on the sound server when too many
requests come in a very short time.
The rule is the following: if the user attempts to create a new
instance/uuid of sound event id that already have 5 instances,
then the request will be ignored and considered as an error.
https://phabricator.endlessm.com/T25273
=> server: Limit to 5 sounds playing simultaneously

src/server.py
A method to set the reference count of a sound to 0.
https://phabricator.endlessm.com/T25111
=> server: Add TermSound method

data/metadata.json
https://phabricator.endlessm.com/T25315
=> sounds: system: Add 'ignore' overlap behavior to bg sounds

data/metadata.json
https://phabricator.endlessm.com/T25710
=> metadata: Fix bg sound typo

.travis.yml, ci/metadata.schema.json
https://phabricator.endlessm.com/T25696
=> CI: Validate metadata.json file

src/server.py
https://phabricator.endlessm.com/T25857
=> server: Always return on a StopSound call

src/server.py
https://phabricator.endlessm.com/T25847
=> server: Hold the server only if a new uuid will be created

src/server.py
https://phabricator.endlessm.com/T25859
=> server: Release player if fade out fails

src/server.py
Instead of delaying the PLAYING state using GLib.timeout_add, just
set the pipeline to the PLAYING state immediately as the PlaySound
call arrives and let the pipeline clock running (playing the
silence for the delay time), but delaying the stream.
https://phabricator.endlessm.com/T25859
=> server: Delay using pad probes

src/server.py
https://phabricator.endlessm.com/T25858
=> server: Remove duplicate code when releasing player structs

src/server.py
https://phabricator.endlessm.com/T26177
=> server: Remove Error signal

tools/check-ffmpeg.sh, tools/convert-sounds.sh, tools/truncate-silence.sh
https://phabricator.endlessm.com/T25614
=> tools: Add script to truncate silence from audio files

data/metadata.json
https://phabricator.endlessm.com/T26158
=> sounds: quests: Hook up FOB3 sound.

tools/truncate-silence.sh
https://phabricator.endlessm.com/T26431
=> tools: Use a different output file as the input file in ffmpeg

src/utils/loggable.py
https://phabricator.endlessm.com/T26153
=> logger: Stringiy message in the PlayerFormatter class

data/metadata.json
https://phabricator.endlessm.com/T25953
=> sounds: shell: Silence FtH sounds

tools/check-ffmpeg.sh
https://phabricator.endlessm.com/T26541
=> tools: Suggest where to get ffmpeg from if ffmpeg not installed

build-flatpak.sh, tools/build-local-flatpak.sh
Copy&pasted from clubhouse/tools/build-flatpak.sh
https://phabricator.endlessm.com/T26556
=> tools: flatpak: Add script to build a local flatpak

src/server.py
https://phabricator.endlessm.com/T26976
=> server: Fix tracking of uuids per bus name

README.md, com.hack_computer.HackSoundServer.appdata.xml, com.hack_computer.HackSoundServer.json.in, meson.build, service/com.hack_computer.HackSoundServer.service.in, src/server.py, tools/build-local-flatpak.sh
This will help to separate the two services
when we migrate existing users.
https://phabricator.endlessm.com/T27400
=> Deploy Hack2: rename game state service

README.md
In the previous PR I've use a script for this rename that doesn't work correctly with object-path, this PR fixes that.
https://phabricator.endlessm.com/T27400
=> Readme: Fix rename object-path

data/metadata.json
https://phabricator.endlessm.com/T28211
=> metadata: Tag talk mood sounds with "ignore" overlap behaviour
